source "https://rubygems.org"

# Webserver Interface
gem 'rack'

# REST-like API Framework
gem 'grape'

# Database ORM
gem 'activerecord'

# Postgres Database
gem 'pg'

# Database Migrations
gem 'standalone_migrations', '>= 6.0'

# Debugger
gem 'pry'

# Static Analysis
gem 'rubocop', require: false

# For BDD tests
gem 'rspec'

# Rack testing: https://github.com/rack/rack-test
# Source: https://github.com/ruby-grape/grape#writing-tests
gem 'rack-test'

# Enhanced rspec matchers (I thought these came packaged with rspec)
gem 'shoulda-matchers'

# Ruby make-like utility
gem 'rake'
